-- 10 tables: no secondary indexes, no foreign keys
CREATE TABLE IF NOT EXISTS t1 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t2 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t3 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t4 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t5 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t6 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t7 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t8 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t9 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t10 (
  id BIGSERIAL PRIMARY KEY,
  ref_id BIGINT,
  payload BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);
